FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY src ./src
COPY migrations ./migrations
COPY seed ./seed
COPY scripts ./scripts

ENV NODE_ENV=production
EXPOSE 5000

CMD ["node", "src/server.js"]
